#!/usr/bin/env python3
"""Bass / Middle / Treble for NAMLite, voiced like the NAM plugin's tone stack.

Same design as NeuralAmpModelerPlugin's BasicNamToneStack (ToneStack.cpp) with
AudioDSPTools' RBJ-cookbook biquads (RecursiveLinearFilter.cpp), run in the
same order, bass -> middle -> treble:

    Bass    low shelf  150 Hz, Q 0.707,           gain 4 dB per step from 5 (+/-20 dB)
    Middle  peaking    425 Hz, Q 1.5 cut/0.7 boost, gain 3 dB per step    (+/-15 dB)
    Treble  high shelf 1800 Hz, Q 0.707,          gain 2 dB per step    (+/-10 dB)

The plugin's 0..10 value is the pedal knob / 10; knob 50 is flat. At flat the
three biquads are an EXACT identity even in float (b0 = 1, b1 = a1, b2 = a2 bit
for bit, so the state stays zero), which the tests check: flat EQ must leave
NAMFull2's output unchanged to the last bit.

WHY A TABLE. The coefficients need pow/sin/cos, and this loader cannot resolve
math-library helpers (a documented freeze). So they are computed here, in
double precision, for every knob position 0..100 of every band, and written as
a const table the pedal only indexes: 3 x 101 x 5 floats, 6 KB. No approximation
anywhere -- each entry is the plugin's own formula evaluated exactly at the
pedal's 44.1 kHz.

    python3 tools/nam_prototype/tone_stack.py OUT_DIR    # writes nam_tone_table.h
"""
import math
import sys
from pathlib import Path

FS = 44100.0
BANDS = ('bass', 'middle', 'treble')


def _params(freq, q, gain_db):
    a = 10.0 ** (gain_db / 40.0)
    w0 = 2.0 * math.pi * freq / FS
    return a, w0, math.sin(w0) / (2.0 * q), math.cos(w0)


def low_shelf(freq, q, gain_db):
    a, w0, alpha, cw = _params(freq, q, gain_db)
    ap, am, r = a + 1.0, a - 1.0, 2.0 * math.sqrt(a) * alpha
    return (a * (ap - am * cw + r), 2.0 * a * (am - ap * cw), a * (ap - am * cw - r),
            ap + am * cw + r, -2.0 * (am + ap * cw), ap + am * cw - r)


def peaking(freq, q, gain_db):
    a, w0, alpha, cw = _params(freq, q, gain_db)
    return (1.0 + alpha * a, -2.0 * cw, 1.0 - alpha * a,
            1.0 + alpha / a, -2.0 * cw, 1.0 - alpha / a)


def high_shelf(freq, q, gain_db):
    a, w0, alpha, cw = _params(freq, q, gain_db)
    ap, am, r = a + 1.0, a - 1.0, 2.0 * math.sqrt(a) * alpha
    return (a * (ap + am * cw + r), -2.0 * a * (am + ap * cw), a * (ap + am * cw - r),
            ap - am * cw + r, 2.0 * (am - ap * cw), ap - am * cw - r)


def design(band, knob):
    """Normalised (b0, b1, b2, a1, a2) for a pedal knob position 0..100."""
    val = knob / 10.0
    if band == 'bass':
        raw = low_shelf(150.0, 0.707, 4.0 * (val - 5.0))
    elif band == 'middle':
        g = 3.0 * (val - 5.0)
        raw = peaking(425.0, 1.5 if g < 0.0 else 0.7, g)
    else:
        raw = high_shelf(1800.0, 0.707, 2.0 * (val - 5.0))
    b0, b1, b2, a0, a1, a2 = raw
    return (b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


def response_db(coefs, freq):
    b0, b1, b2, a1, a2 = coefs
    z = complex(math.cos(2 * math.pi * freq / FS), -math.sin(2 * math.pi * freq / FS))
    h = (b0 + b1 * z + b2 * z * z) / (1 + a1 * z + a2 * z * z)
    return 20 * math.log10(abs(h))


def write_table(out_dir: Path, half: bool = False) -> Path:
    """half=True: one row per EVEN knob (0, 2, ..., 100), 51 rows -- 3 KB less,
    for the pedal's ZDL size cap. Even knobs are unchanged; odd knobs play the
    next even row (nam_tone_row). Knob 50 stays the exact identity."""
    out = Path(out_dir) / 'nam_tone_table.h'
    rows = []
    knobs = range(0, 101, 2) if half else range(101)
    for band in BANDS:
        rows.append('  {  /* %s */' % band)
        for k in knobs:
            c = design(band, k)
            rows.append('    {' + ','.join('%.9ef' % x for x in c) + '},')
        rows.append('  },')
    out.write_text(
        '/* Generated by tools/nam_prototype/tone_stack.py -- do not edit.\n'
        ' * NAM-plugin tone stack (bass 150 Hz shelf, middle 425 Hz peak, treble\n'
        ' * 1.8 kHz shelf), RBJ biquads at 44.1 kHz, one row per knob 0..100:\n'
        ' * {b0, b1, b2, a1, a2}, normalised by a0. Knob 50 is exactly flat. */\n'
        + ('#define NAM_TONE_STEP 2\n' if half else '#define NAM_TONE_STEP 1\n')
        + 'static const float nam_tone[3][%d][5] = {\n' % len(knobs) + '\n'.join(rows) + '\n};\n')
    return out


if __name__ == '__main__':
    p = write_table(Path(sys.argv[1]))
    print(f'wrote {p}')
    for band, f in (('bass', 100), ('middle', 425), ('treble', 6000)):
        print(f'  {band:<7} at {f:>4} Hz: knob 0 {response_db(design(band, 0), f):+6.1f} dB, '
              f'50 {response_db(design(band, 50), f):+5.2f} dB, 100 {response_db(design(band, 100), f):+6.1f} dB')
