"""CabIR 0.30: one cab per effect file -- 16 slot templates and a reference fill.

    python3 src/hardware_probes/cab_ir/build.py --template
        Compile the engine once and link it into SLOTS slot templates, each its
        own effect identity (FXID 930..945, CabSl01..CabSl16), like the NAM
        capture slots. Writes tools/cab_template/{slot-NN.bin, cab.json,
        CabIR.png}. Every template holds a flat "no cab" (unit FIR, identity
        biquads, gain 1).

    python3 src/hardware_probes/cab_ir/build.py a.wav [b.wav ...] [--names sm57,sm58]
        Fit each IR (fit.py) and fill slots 1..n exactly as the browser loader
        does (fill_cab below) into build/probes/cab-ir/. The reference the
        loader's JS is tested against; validate.py runs on slot 1.

Why separate files and not 0.20's bank of 8 behind a Cab knob: a patch stores a
knob POSITION, so reordering or removing a cab in the bank silently changed
which cab every patch played. A slot is an effect ID; it never moves. It is
also smaller (one cab's data, no selector) and not limited to 8.

The templates are linked with unique marker values in the coefficient arrays
so their file offsets can be found by byte search (each must occur exactly
once); the markers are then overwritten. Code and relocations never depend on
the data. Do not publish user-owned IRs or fits of them (dist/C??*.ZDL is
gitignored).
"""
import argparse, hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = ROOT / 'build/probes/cab-ir'
TPL = ROOT / 'tools/cab_template'
sys.path[:0] = [str(ROOT / 'build'), str(HERE)]
import fit

VERSION = '0.30'
SLOTS, TAPS, NBQ = 16, 32, 6
FXID0 = 929                                      # slot s -> FXID 929 + s (930..945)
RESO = dict(freq=140.0, q=1.0, range_db=6.0)     # the cab's low bump (Mesa V30 target peaks ~140 Hz)
PRES = dict(freq=2800.0, q=0.8, range_db=6.0)    # presence region, below the cab's roll-off
PARAMS = [dict(name='Mix', max=100, default=100), dict(name='Level', max=100, default=50),
          dict(name='Reso', max=100, default=50), dict(name='Pres', max=100, default=50)]
FLAT_SOS = [1.0, 0.0, 0.0, 0.0, 0.0]
DSP_COST = 10.0     # ~5% of NAM's cost (818 vs ~15k emulated cycles); see package_eq_templates.DSP_COST
FLAT = dict(fir=[1.0] + [0.0] * (TAPS - 1), sos=[FLAT_SOS] * NBQ, gain=1.0)


def knob_table(f0, q, range_db):
    """101 rows {b0,b1,b2,a1,a2}; row 50 is the exact identity (flat knob = no change)."""
    return [FLAT_SOS if k == 50 else list(fit.peak(f0, (k - 50) / 50 * range_db, q)[[0, 1, 2, 4, 5]])
            for k in range(101)]


def c_floats(v):
    return ','.join(format(float(x), '.9e') + 'f' for x in v)


def markers():
    return dict(fir=[1000.0 + t for t in range(TAPS)],
                sos=[[3000.0 + 5 * j + c for c in range(5)] for j in range(NBQ)], gain=5000.0)


def write_header(path, cab=None):
    """cab=None: the template's marker values; else a cab dict, for a host
    build that must match a filled slot exactly (validate.py)."""
    c = cab or markers()
    h = [f'#define CAB_TAPS {TAPS}u', f'#define CAB_NBQ {NBQ}u',
         f"static const float cab_gain[1] = {{{c_floats([c['gain']])}}};",
         f"static const float cab_fir[CAB_TAPS] = {{{c_floats(c['fir'])}}};",
         'static const float cab_sos[CAB_NBQ][5] = {' + ','.join('{' + c_floats(r) + '}' for r in c['sos']) + '};']
    for name, spec in (('cab_reso', RESO), ('cab_pres', PRES)):
        h.append(f'static const float {name}[101][5] = {{' +
                 ','.join('{' + c_floats(r) + '}' for r in knob_table(spec['freq'], spec['q'], spec['range_db'])) + '};')
    path.write_text('/* generated by build.py -- do not edit */\n' + '\n'.join(h) + '\n')


def f32(values):
    return np.asarray(values, '<f4').tobytes()


def make_templates():
    from linker import LinkerConfig, ObjFile, link, params_from_manifest
    from capture_art import picture
    from make_em_thumbnails import render
    from zdl import Zdl
    from gen_init_materialize import _read_elf_sections
    from zdl_size_guard import check as size_check
    work = OUT / 'template'
    work.mkdir(parents=True, exist_ok=True)
    write_header(work / 'cab_data.h')
    ti = Path('/Applications/ti/ti-cgt-c6000_8.5.0.LTS')
    obj = work / 'cab.obj'
    subprocess.run([str(ti / 'bin/cl6x'), '--c99', '-O2', '-mv6740', '--abi=eabi', '--mem_model:data=far',
                    '--fp_mode=strict', '--fp_reassoc=off', f'--include_path={ti}/include', f'--include_path={work}',
                    f'--include_path={ROOT}/src/airwindows/common', '--keep_asm', f'--asm_directory={work}', '-c',
                    str(HERE / 'cab_ir.c'), f'--output_file={obj}'], check=True)
    o = ObjFile(obj)
    assert not any(s['name'] and not s['shndx'] for s in o.symbols), 'unresolved helper symbol'
    for s in o.sections:
        if s['name'] in ('.text', '.bss', '.far', '.fardata') or s['name'].startswith('.switch'):
            assert not s['size'], f"unexpected section {s['name']}"
    TPL.mkdir(exist_ok=True)
    for old in TPL.glob('*.bin'):
        old.unlink()
    mk = markers()
    slots, texts = [], set()
    for s in range(1, SLOTS + 1):
        ident = f'CabSl{s:02d}'
        zdl = work / f'slot-{s:02d}.ZDL'
        link(LinkerConfig(effect_name=ident, audio_func_name='Fx_REV_CabIR', gid=8, fxid=FXID0 + s,
                          params=params_from_manifest(PARAMS), obj_path=obj, output_path=zdl,
                          fxid_version=VERSION.encode(), screen_image=picture('IR'), materialize_init=True,
                          use_object_edit_handlers=False, synthesize_linesel_edit_handlers=True,
                          synth_edit_start_index=2, knob3_blob_path=str(work / 'unused'), dsp_cost=DSP_COST))
        data = bytearray(zdl.read_bytes())
        offs = {}
        for key, block in (('fir', f32(mk['fir'])), ('sos', f32(mk['sos'])), ('gain', f32([mk['gain']]))):
            assert data.count(block) == 1, f'slot {s}: {key} markers not found exactly once'
            offs[key] = data.index(block)
        assert data[68:72] == VERSION.encode(), 'version field not at 68'
        z = Zdl.load(zdl)
        secs = _read_elf_sections(z.elf)
        cs, tx = secs['.const'], secs['.text']
        texts.add(hashlib.sha256(z.elf[tx['offset']:tx['offset'] + tx['size']]).hexdigest())
        name_at = z.elf[cs['offset']:cs['offset'] + cs['size']].index(b'OnOff\0') + 20 + z.header_size + cs['offset'] + 48
        assert data[name_at:name_at + len(ident)] == ident.encode(), 'display-name field not where expected'
        slot = dict(slot=s, fxid=FXID0 + s, file=f'slot-{s:02d}.bin', fir_offset=offs['fir'],
                    sos_offset=offs['sos'], gain_offset=offs['gain'], name_offset=name_at)
        flat = fill_cab(bytes(data), slot, FLAT)
        (TPL / slot['file']).write_bytes(flat)
        size_check(TPL / slot['file'])
        slot.update(bytes=len(flat), sha256=hashlib.sha256(flat).hexdigest())
        slots.append(slot)
    assert len(texts) == 1, 'audio code differs between slots'
    if s == SLOTS:
        render(zdl)
        (TPL / 'CabIR.png').write_bytes(zdl.with_suffix('.png').read_bytes())
    (TPL / 'cab.json').write_text(json.dumps(dict(
        format=2, engine=f'CabIR {VERSION}: one cab per file, {TAPS}-tap FIR + {NBQ} biquads, Reso/Pres',
        output_version=VERSION, version_offset=68, taps=TAPS, biquads=NBQ, sample_rate=44100, dsp_cost=DSP_COST,
        params=[p['name'] for p in PARAMS], reso=RESO, pres=PRES, slots=slots), indent=2) + '\n')
    print(f'templates: {SLOTS} slots (FXID {FXID0 + 1}-{FXID0 + SLOTS}), {slots[0]["bytes"]} bytes each, '
          f'.text identical in all slots')


def fill_cab(template, slot, cab, name=None):
    """Write one cab (and optionally its display name) into a slot template.
    Mirrors tools/cab_loader.js fillCab."""
    out = bytearray(template)
    assert len(cab['fir']) == TAPS and len(cab['sos']) == NBQ
    out[slot['fir_offset']:slot['fir_offset'] + 4 * TAPS] = f32(cab['fir'])
    out[slot['sos_offset']:slot['sos_offset'] + 20 * NBQ] = f32(cab['sos'])
    out[slot['gain_offset']:slot['gain_offset'] + 4] = f32([cab['gain']])
    if name:
        label = ('CAB-' + name).encode()
        assert len(label) <= 12
        out[slot['name_offset']:slot['name_offset'] + 12] = label + bytes(12 - len(label))
    return bytes(out)


def file_name(slot, name):
    """C<2-digit slot><up to 5 chars of name>.ZDL: <= 8 characters and unique per
    slot (the pedal truncates basenames to 8 and freezes on duplicates)."""
    return f'C{slot:02d}{name[:5]}.ZDL'


def cab_from_fit(f):
    sos = [list(s[[0, 1, 2, 4, 5]]) for s in f.sos]
    for s in sos:                                  # poles inside the unit circle after float32 rounding
        a1, a2 = np.float32(s[3]), np.float32(s[4])
        assert abs(a2) < 1 and abs(a1) < 1 + a2, f'unstable after float32 rounding: {s}'
    return dict(fir=list(f.fir), sos=sos, gain=float(f.gain))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--template', action='store_true')
    ap.add_argument('wavs', type=Path, nargs='*')
    ap.add_argument('--names', default='')
    a = ap.parse_args()
    if a.template:
        make_templates()
        return
    assert 1 <= len(a.wavs) <= SLOTS, f'1..{SLOTS} IRs'
    manifest = json.loads((TPL / 'cab.json').read_text())
    names = [n for n in a.names.split(',') if n] or [w.stem.replace(' ', '')[:8].lower() for w in a.wavs]
    OUT.mkdir(parents=True, exist_ok=True)
    cabs, report = [], []
    for i, w in enumerate(a.wavs):
        slot = manifest['slots'][i]
        template = (TPL / slot['file']).read_bytes()
        assert hashlib.sha256(template).hexdigest() == slot['sha256'], 'run --template first'
        ir = fit.load(w)
        f = fit.fit(ir, TAPS, NBQ - 2)
        cab = cab_from_fit(f)
        cabs.append(cab)
        fn = file_name(slot['slot'], names[i])
        (OUT / fn).write_bytes(fill_cab(template, slot, cab, names[i]))
        report.append(dict(slot=slot['slot'], fxid=slot['fxid'], file=fn, source=w.name,
                           source_ms=round(len(ir) / fit.FS * 1000, 1), fit_rms_db=round(f.error_db(), 2),
                           fit_worst_db=round(f.max_error_db(), 2)))
    (OUT / 'slot1').mkdir(exist_ok=True)
    c = cabs[0]
    write_header(OUT / 'slot1' / 'cab_data.h', dict(fir=np.float32(c['fir']).tolist(),
                                                    sos=np.float32(c['sos']).tolist(),
                                                    gain=float(np.float32(c['gain']))))
    np.savez(OUT / 'model.npz', fir=np.array([c['fir'] for c in cabs]), sos=np.array([c['sos'] for c in cabs]),
             gain=np.array([c['gain'] for c in cabs]),
             reso=np.array(knob_table(RESO['freq'], RESO['q'], RESO['range_db'])),
             pres=np.array(knob_table(PRES['freq'], PRES['q'], PRES['range_db'])))
    r = dict(version=VERSION, cabs=report, mul_per_sample=TAPS + 5 * (NBQ + 2), hardware='pending')
    (OUT / 'preparation.json').write_text(json.dumps(r, indent=2) + '\n')
    print(json.dumps(r, indent=2))


if __name__ == '__main__':
    main()
